services:
  sina:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_ALLOWED_EMAILS: ${VITE_ALLOWED_EMAILS}
      NODE_ENV: ${NODE_ENV}
    image: sina
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.sina.entrypoints=web,websecure
      - traefik.http.services.sina.loadbalancer.server.port=3000
      - traefik.http.routers.sina.rule=Host(`sina.silasbeckmann.de`)
      - traefik.http.routers.sina.tls=true
      - traefik.docker.network=traefik_proxy-net
      - traefik.http.middlewares.sina.headers.SSLRedirect=true
      - traefik.http.middlewares.sina.headers.STSSeconds=315360000
      - traefik.http.middlewares.sina.headers.browserXSSFilter=true
      - traefik.http.middlewares.sina.headers.contentTypeNosniff=true
      - traefik.http.middlewares.sina.headers.forceSTSHeader=true
      - traefik.http.middlewares.sina.headers.SSLHost=${DOMAIN_NAME:-sina.silasbeckmann.de}
      - traefik.http.middlewares.sina.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.sina.headers.STSPreload=true
      - traefik.http.routers.sina.middlewares=sina@docker
    networks:
      - traefik_proxy-net
    
networks:
  traefik_proxy-net:
    external: true